\c melhorias

\i seeds/areas.sql

 INSERT INTO melhorias (area, redmine, ticket, descricao, prazo_acordado, prazo_legal, demanda_legal, gravidade, urgencia, tendencia, entrega_em) VALUES 
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13233, null, 'REFISA Sapiranga', '2019-05-02', null, 'f', null, 1, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12159, null, 'Vencimento ISS FIxo (Dewes update)', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13311, null, 'Inclusão de CDA na fila do CRA a partir de um arquivo TXT', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10518, null, 'Inclusão de CDA na fila do CRA - Inclusão Manual - mostrar para o usuário as CDAs que já foram incluídas', '2019-05-31', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10513, null, 'Listar data correta do envio da CDA para a fila do CRA na consulta', '2019-05-31', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'recalculo IPTU anos anteriores (civitas fase 3)', '2019-10-31', null, 'f', null, 5, null, 10),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'integração dos dados de RI lançado na averbação com o cadastro do imóvel', '2019-05-30', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12850, null, 'Configuração de documentos da certidões (taquari)', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 11152, null, 'Anulação de Parcelamento de Cob. Adm - Sistema deve gerar uma CDA e uma inicial por origem de parcelamento que foi inscrito em dívida.', '2019-07-31', null, 'f', null, 5, null, 7),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12778, null, 'Identificar inscrições que não possuem local fixo (cadastro/calculo alvara)', '2019-07-31', null, 'f', null, 5, null, 7),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10533, null, 'Prescrição de Débitos - validar se o débito pode ser prescrito levando em conta se foi parcelado, ou se foi protestado, ajuizado', '2019-07-31', null, 'f', null, 5, null, 7),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12676, null, 'Ao anular parcelamento, a divida de origem não pode ser Parcelada na mesma regra do parcelamento anulado', '2019-05-31', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 11088, null, 'CDA de saldo de parcelamento (11152) - quando anula tem que lançar observação na divida->v01_obs... prescrição...', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Modulo Fiscal - trazer alterações de Niterói para o sistema', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10902, null, 'Parcelamento de honorários', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10527, null, 'Reativar Parcelamento - Liberar menu para o cliente', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13263, null, 'txt Banco do Brasil RCB800', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12852, null, 'Isenção para cadastro mobiliário - Permitir cadastrar isenção de taxas de vistorias e alvará para determinadas inscrições.', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10521, null, 'Inscrição em Dívida - Na tela de inscrição em dívida ativa listar o exercício do débito', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Tipos de promitentes / responsáveis pelo imóvel', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Trigger de niteroi para registrar nas ocorrência todas as alterações do imóvel', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'link matriculas cadastradas colocar coluna com data da baixa da matrícula', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, 1033085, 'QRcode no alvará', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13088, 1054307, 'Atualização do valor do crédito com juros', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Baixa manual - valor atualizado (Ver com Dewes)', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10529, null, 'PPF - notificação com boletos com custas', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10528, null, 'PPF - impressão de boletos com ou sem custas/honorários no dbpref', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10530, null, 'Cancelamento de Débitos por depto', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10515, null, 'Alerta na anulação de parcelamento', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 5368, null, 'Declaração de quitação de ITBI e taxas', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 5361, null, 'Parcelamento de ITBI', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10663, null, 'Civitas - Emissão de Notificações - fase 3', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13312, null, 'Guardar o nome dos envolvidos no débito no momento da geração da CDA', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'regin gaucho/rede sim', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Consulta calculo IPTU - visualizar aliquotas taxa de lixo', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Edição da BIC para gerar com as informações desejadas', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Adicionar aba de averbação na manutenção de imóvel', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 12808, null, 'Ajuste na alteração de diversos e de cobrança administrativa', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 13245, null, 'Controle de Leilão Judicial', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), 10341, null, 'Certidão de Baixa - Taquari', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Controle para não permitir emitir boleto de débito quando a consulta pelo proprietario secundário do imóvel', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Unificar os plugins do CRA de Niterói e do RS (ajustar plugin de Niteroi para buscar as praças da tabela Dê - Para).', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'exceção na geração de carnẽ', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, '"cadastro de e-mail para envio de boletos para o contribuinte Sapiranga/Arroio"', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'atualização de endereço de entrega pelo dbpref', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'atualização de cgm pelo dbpref', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, '"restituição de pagamento indevido - Sapiranga (Leandro)\ncontabilziar como arrecadação de dedução de receita gerando documento para contribuinte\nTicket#1025195 — CONTABILIDADE - Deduções da Receita x Tributário"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'automatizar calculo para tecnico de implantacao - formulas', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'incorporação', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'mobile nota prestador de serviço', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'regin', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'geo', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Assinatura digital na CDA', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Tributário'), null, null, 'Problemas na importacao de arquivo Retencao', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Atualizar as Fichas do CDS E-SUS', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Integração com CNES - atualização layout', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, '"Melhorias no Laboratório (09 itens a serem desenvolvidos no módulo)\nCarazinho"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Melhorias no Agendamento de Consultas e Exames para atender Tramandaí', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Controle de Cotas no Agendamento de Consultas', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Integração com SIGTAP', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Incluir dados em FAA', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'CMD - Conjunto Mínimo de Dados', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'Consultas Odontológicas - Odontograma', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Saúde'), null, null, 'tablets - utilizar sistema/fichas/visitas offline', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Instabilidade módulo Material', '2019-12-31', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"Integração contábil Almox x Contabilidade ser por fechamento\n\nnão efetuar os lançamentos automaticamente"', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 9029, null, '"chamamento público PNAE\nmodalidade de licitação que permite vários fornecedores para o mesmo item"', null, null, 't', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Deliberação 277', '2019-04-30', null, 't', null, 1, null, 4),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 12295, null, '"Incorporar bens Fundo/MP Rondonia\nbens adquiridos por uma Instituição que será incorporado em outra (com lançamentos contábeis)"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '3 Fase BID', '2019-05-31', null, 't', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"Cedência de saldo de Registro de Preço para departamento não estimantes\npermitir que departamentos que nãó fizeram estimativa no processo inicial possam participar do registro de preço"', null, null, 't', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Rotina para criação de atas e editais com formato padrão do sistema e corpo digitavel', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Emissão de etiquetas patrimonio Impressora Brother (São Borja e Bagé)', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Anulação de empenho Resgitro de Preço, retornar saldo disponivel', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"Abertura de processos pelo contribuinte\npré-processo via internet"', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'MP/AC Impressão total do processo administrativo - folhar processo', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'sigfis contratos - cliente quer prazo', null, null, 't', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Transferencia de Bens centralizado com recebimento automático (MPRO)', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"cadastro CGM link e busca pelo site da receita\ncorreios\nwsreceita"', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"Campos do Licitacon terem interatividade e consultas\nlimitação upload arquivos"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Ouvidoria mobile', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 8452, null, 'GED e assinatura eletrônica', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 8748, null, '"Julgamento de licitações por maior nota (julgamento técnico), valor\ntécnica vs preço"', null, null, 't', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Leitor de código de barras em arquivo txt, atender rotina de levantamento patrimonial', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'rotina de levantamento patrimonial permitir executar procedimentos', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 5429, null, 'Rotina de importação de arquivo para reavaliação', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 5462, null, 'Relatório Registro de Preço filtro por Depart, não emite', '2019-07-31', null, 'f', null, 5, null, 7),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, '"Adjudicação ser por itens na Licitação\nparcial"', null, null, 't', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), 5502, null, 'Rotina de Solicitação de compras, ter melhor usabilidade', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Entrada de ordem de compra com importação do xml NF-e', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Patrimonial'), null, null, 'Foto nos Bens patrimoniais', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'modulo novo que deve ser criado: segurança e medicina do trabalho - SST e-social (+- 10 demandas)', '2019-12-01', null, 't', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-1065 - tabela de equipamentos de proteção', '2019-12-02', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2241 - Insalubridade, Periculosidade e Aposentadoria Especial', '2019-12-03', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2240 - Condições Ambientais do Trabalho - Fatores de Risco', '2019-12-04', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2220 - Monitoramento da Saúde do Trabalhador', '2019-12-05', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2210 - Comunicação de Acidente de Trabalho', '2019-12-06', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-1060 - Tabela de Ambientes de Trabalho', '2019-12-07', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'Melhorias Clin (+- 30 demandas)', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13337, null, 'Assentamento 0110-abono para fins disciplinares', '2019-05-27', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13333, null, 'manutenção dos eventos do ponto', '2019-05-19', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13394, null, 'melhoria na rotina de encerramento do periodo do ponto', '2019-05-27', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13395, null, 'melhoria na reabertura e encerramento da efetividade', '2019-05-10', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13411, null, 'melhoria na manutenção da escala do funcionário', '2019-05-27', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13397, null, 'trazer logs do processamento do ponto na tela', '2019-05-10', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13410, null, 'manutenção individual do ponto saber se a marcação é digitada, gerada ou eletronica', '2019-05-27', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13412, null, 'na tela de manutenção individual do ponto ter a opção de mover a marcação de um dia para o outro', '2019-05-10', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13414, null, 'Melhoria no assentamento de efetividade', '2019-04-25', null, 'f', null, 5, null, 4),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13415, null, 'Na tela de assentamento de efetividade alertar quando for lançar um assentamento e já tenha um lançamento no mesmo dia', '2019-06-14', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13417, null, 'Banco de dados de férias', '2019-09-30', null, 'f', null, 5, null, 9),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13432, null, 'Relação RSC - Extrato da previdência', '2019-05-27', null, 'f', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13433, null, 'Campo salario no cadastro do servidor para atualização da CTPS', '2019-10-30', null, 'f', null, 5, null, 10),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13434, null, 'Melhoria no fechamento da efetividade-logs', '2019-06-10', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 13435, null, 'Alteração e exclusão de assentamentos em lote', '2019-06-10', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'Resumo de rubricas das férias', '2019-10-30', null, 'f', null, 5, null, 10),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - NDE 02/2018 empregadores e tabelas', '2019-12-07', null, 't', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - NDE 02/2018 servidores', '2019-12-08', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - NDE 02/2018 periódicos e não períodicos', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S1202 - Folha orgãos públicos', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S1207 - pagamento de beneficios', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2410 - ', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2420', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2416', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2405', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2400', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - NDE 03/2019', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial - S-2231', '2019-12-09', null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"trazer eSocial para o e-Cidade\nvice-versa"', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, 1049449, '"Melhoria do Controle de Férias - Paty\ncliente quer relatório que demonstre o próximo dias que o servidor tem direito a férias, e para isso devemos utilizar o controle de direitos"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 1, null, '"Segregação de Bases - MPRO\nUm exemplo é um servidor que estava de auxilio doença por mais de 15 dias e retorna..."', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 2, null, 'Pensão Alimentícia - calculo pelo bruto - MPRO', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 3, null, '"Pensão Alimentícia - Base única para as pensões calculadas sobre o líquido\n- simulação do IR da pensão + desconto judicial + pensao extrajudicial - MPRO"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), 4, null, 'Folha PAE - MPRO - copiar folhas e pontos (suplementar)', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"férias - MPRO e demais clientes\npegar estrutura TCE e ajustar/refatorar..."', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'Refatoração do calculo da folha', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"refatoração da geração da RAIS, visto que não irá rodar em clientes maiores\nnão roda em natal"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'eSocial no portal do servidor - recadastramento', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'Prorrogação licença gestante', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, 'Procedimentos > Implantação: funcionar também na estrutura Complementar/Suplementar', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"remuneração periodos anteriores - esocial\ncomo recalcula pagamentos retroativos não atende o e-social\ne-social quer saber mes a mes o valor retroativo (IR/INSS)"', null, null, 't', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"Possibilidade de ser enviado as tabelas (cargo/função/rubrica individual) como a melhoria do envio por matricula\ne-social"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Folha'), null, null, '"portal servidor mobile: contracheque...\nmulti-plataforma\ntestar"', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 5607, null, '"retificação lançamento\ncorrigir lançamento e não apagar"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"gestão de diárias (sigfis/portal da transparencia)\nempenho diárias estimativo / prestação de contas (MPRO)\nSantarem"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'planilhas SIOPS/SIOPE', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'Deliberação 277 - RJ - TCE', '2019-04-30', null, 'f', null, 4, null, 4),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Agregador MSC\nCamara..."', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 12933, null, '"Possibilidade de realizar a baixa de mais de uma OP para um mesmo pagamento (seja guia/boleto/etc).\n1 boleto para várias OPs (energia eletrica atrasada)"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 10853, null, '"Gestão de Alterações Orçamentárias\nSuplementações\n- suplementação entre elementos não precisa decreto"', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Crítica na origem dos problemas que existem ao invés de criticar na emissão do arquivo de pagamento\n- digitos conta, CNPJ invalido...\n\n* Helio comentou que em Natal critica CNPJ na agenda"', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"GRM Intra - capacidade de realizar as retenções envolvendo receitas do município através de GRM Intra.\n- várias instituições\n"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Poderemos neste caso fazer uma melhoria no decorrer do processo que consiste em:\n** permitir o lançamento manual envolvendo contas de banco ou limite de saque', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Fazer com que o procedimento de concessão de transferência financeira grave lançamentos nas instituições de origem e destino.\nQuando a Prefeitura estiver concedendo, por exemplo uma transferência financeira para a Câmara, devem ser escriturados os seguintes lançamentos:\n\nNA PREFEITURA\n\nD - 3.5.XX - VPD\nC - BANCO\n\nNA CÂMARA\n\nD - 1.1.3 xx - CONTAS A RECEBER\nC - 4.5.XX - VPA\n\nQuando a Câmara receber, fazer os lançamentos:\n\nD - BANCO\nC - 1.1.3.XX - CONTAS A RECEBER\n\n* Helio comentou que em Natal em algo automático"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 12954, null, 'Feedbacks da consulta geral: trazer o estrutural ao invés do código da conta, trazer a data inicial preenchida por padrão como 01/01 do exercício corrente, ter totalizador por colunas e saber os lançamentos que compõe um conta corrente', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Não permitir entrada de valores em conta que não pertencem aos documentos/eventos executados.\nsegurança/consistencia... configuração do plano de contas"', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Elaboração padrão de contas\ndeixa inverter saldo..."', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Implementar uma configuração no plano de contas que não permita a inversão do saldo. Alguns itens fundamentais:\n\n1) validar conforme o plano de contas PCASP padrão se a conta é de natureza devedora, credora ou mista', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Verificar saldos da contabilidade\n- não ter virada de exercicio para ter saldo inicial (todas as contas) - saldo inicial balancete de verificação"', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'As contas que não zeram no encerramento do exercício devem transpor automaticamente seus saldos para o exercício seguinte sem necessidade de rotinas para importação tais como as que rodamos no procedimento de encerramento. Caso haja lançamento no ano anterior (obviamente com o período aberto antes de encerrar), os saldos devem ser atualizados automaticamente.', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'Realizar consistências para monitorar regras de negócio e evitar problemas (alguns históricos como PAD/SIAI)', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 12931, null, 'Gestão de Vinculação de Pagamento', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Aviso/Notificação de pagamentos que as unidades enviaram para ser pago pelo limite de saque.\nmessageria"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'Integração com tributos - dívida ativa e patrimônio', '2019-11-30', null, 't', null, 5, null, 11),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Folha e MCASP\nférias/13º/licenca premio são apropriações por competencias e não mais provisões\nmensal"', '2019-11-30', null, 't', null, 5, null, 11),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'Planejamento e controle - programação financeira e cronograma de desembolso', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Precisamos que o Balancete de Verificação (ou uma nova versão do Balancete de Verificação) tenha a possibilidade de ser detalhado por conta corrente.\n\nNatal precisa balancete de verificação por UG"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"SEM TICKET - Correção da virada dos tipos de restos a pagar (melhoria)\nSapiranga/Leandro"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'Promover automatizações de lançamentos a partir da carga do extrato baseados na identificação de operações neste extrato. Exemplo: identificar qual o documento ou histórico que o banco utiliza para repassar o FPM e associar uma regra que automatize a criação e autenticação de planilha neste dia baseado neste registro.', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Melhorar o gerenciamento do cadastro do plano de contas orçamentário e plano de contas PCASP principalmente quando as contas tiverem relacionamento entre outros módulos. Exemplos:\n\n** plano orçamentário de receita ligado a previsão no Orçamento e receita na tesouraria', null, null, 'f', null, null, 3, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Ticket#1056001 — CONTABILIDADE-PROBLEMAS NO RELATÓRIO DE RESTOS A PAGAR\nEste item se refere a limitação da aba de filtro na busca de dados que não estão no orçamento do ano atual\n\nSAPIRANGA"', '2019-06-01', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"Relatório de Saídas por departamento (Contabilidade) / Implementação de Relatório Sintético de Saídas por Departamento\n\nAlmoxarifado Sapiranga\nPrazo março\n\nrevisar com Peres"', '2019-06-15', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), 12775, null, 'Trazer a conta padrão sugerida na agenda (Jô)', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'EFD Reinf (10)', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, '"eContas Santarem\nSIGAP Porto Velho"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'terminar as integrações', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'melhorar experiencia usuario', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Financeiro'), null, null, 'auditoria/mensageria', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 9121, null, '"substituição professor - hoje tem que substituir todas as disciplinas\n- Helio pediu para gerar assentamento da substituiçõ - integrado"', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, '"confirmação da efetivação da matrícula\n- recusa da designação do aluno"', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, '"novo ensino\n\nnovoensinomedio.mec.gov.br"', null, null, 't', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 8747, null, 'Paginação e Tomo no cadastro de acervos (Biblioteca Bagé)', '2019-04-30', null, 't', null, 5, null, 4),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 5514, null, 'Número da coleção/série (Biblioteca Bagé)', '2019-05-31', null, 't', null, 5, null, 5),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 9122, null, 'Permissão para efetuar a manutenção do histórico escolar (Natal)', null, null, 't', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 10707, null, 'Diário de Classe parcial de turma integral (Arroio do Sal)', null, null, 't', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, '"Rodar designação automaticamente de acordo com o número de vagas disponíveis nas escolas. Gerar relatório com o log do que foi realizado.\nMatricula online."', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, '"Plugin SMS\nVerificar como funciona a questão de envio de SMS. Enviar SMS quando o aluno for alocado, atualmente temos o plugin que faz isto na rotina de designação, no entanto o mesmo não contempla a rotina de manutenção da lista de espera.\n"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 11576, null, '"Desabilitar escolas para a Pré-Matrícula\nMatricula online."', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 12162, null, '"Vagas na manutenção da lista de espera quando turno é integral e só tem vaga parcial.\nMatricula online."', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 11571, null, '"Matrícula Online: permissão para alterar o campo Vagas\nbloquear para que somente o administrador do matricula online possa alterar a quantidade de vagas"', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 10710, null, '"Relatório sintético da Lista de Espera\nMatricula online."', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 11574, null, '"Matrícula Online: Totalizadores nos relatórios.\nMatricula online."', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 11577, null, '"Matrícula Online: Consulta geral de inscrições.\nMatricula online."', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), 11578, null, '"Matrícula Online: Relatório com total de candidatos alocados.\nMatricula online."', null, null, 'f', null, 3, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'Matrícula online - consulta inscrição (exigir CPF e protocolo e não permitir consultar inscrições de fases fechadas, inscrições excluidas. Alocados via processo, ver sobre não aparecerem ou aparecer para qual escola ou observação.', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'mensageria transferência/atestado de vaga/alocação', null, null, 'f', null, 2, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'portal do aluno acesso pais', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'portal do aluno agenda de atividades / recados para os pais', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'ajuste relatório Paty', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'demandas tramandai - Andrios', null, null, 'f', null, 4, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'mobile chamada pelo celular', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'Alimentação escolar - novo cadastro de tipos de preparo', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'geração da grade de horários professores automático', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'acompanhamento alunos necessidades especiais (desenvolvimento)', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'app educação infantil', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'carteira escolar (linha escolar, biblioteca)', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Educação'), null, null, 'caderno digital - AVA - atividades extras', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Migração CVS -> Git (Também em ''configurações)', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Times por área de negócio', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Retomar wiki para fomentar gestão do conhecimento', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Criar definição de urgência para gestão da entrada de tarefas pelo processo normal', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Retomar DBTalks', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Realizar dinâmica entre desenvolvimento e suporte para estimular colaboração entre áreas', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Kaizen'), null, null, 'Criar cronograma global entre áreas de negócio e técnicas (obrigações, reuniões etc)', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'php 7', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'git', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'e-cidade voltado a serviços (API) / base mobile', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'MP/AC - Login via assinatura digital', '2019-08-31', null, 'f', null, 5, null, 8),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'MP/AC - Integração com AD, manutenção de usuários e senhas', '2019-09-30', null, 'f', null, 5, null, 9),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'melhorias gerador de relatórios', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'nivelamento Niteroi', null, null, 'f', null, 5, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, '"GED\nfalar com Hélio sobre prestação de contas/diárias"', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'assinatura eletrônica alvará/portarias', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'ouvidoria web/mobile bagé', '2019-06-30', null, 'f', null, 5, null, 6),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'desativar menus descontinuados', null, null, 'f', null, null, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, '"limitação imagens/upload\nCDN - não gravar mais no banco\ngestão"', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, 'Alteração da data do sistema não deve alterar a data do LOG (Data do Servidor)', null, null, 'f', null, 1, null, 12),
((SELECT id FROM area WHERE descricao ilike 'Configurações'), null, null, '"Permitir que o sistema fique em uma data específica sem precisar alterar a data do servidor\npara todos os usuarios"', null, null, 'f', null, 1, null, 12)
;

\i seeds/after.sql